### PR TITLE
Default error handler behaivour changed

### LINKED ISSUE #155: The app crashes on database errors

### PR DESCRIPTION
**Pull request by saracalihan**
## Description
If an error other than `ApiError` occurs, it logs it and then passes it to the express's default error handler

Fixed #155 
**Console**: 
Screenshot_20230419_193556

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: src/Builders/RouterBuilder.ts [hunk 1]
```diff
@@ -290,14 +290,11 @@ class RouterBuilder {
...
-            error: "An error occurredxx.",
-          });
-        }
-
-        throw error;
+        // We should log error and send general error response
+        LogService.getInstance().error(`SERVER ERROR: ${JSON.stringify({...error, message: error.message}, null, '  ')}`);
+        res.status(StatusCodes.INTERNAL_SERVER_ERROR).json({
+          error: "An error occurredxx.",
+        });
```
Comment (ozziest) [inline src/Builders/RouterBuilder.ts:297]: We should move production checks to the `axe-api-template`.

**Review by ozziest — CHANGES_REQUESTED** [review]

**Review by ozziest — CHANGES_REQUESTED** [review]
As we talked about in pair programming, we need to provide developers that they can handle errors.

**Comment by saracalihan** [comment]
> As we talked about in pair programming, we need to provide developers that they can handle errors.

They can handle it with an express error handler in the source code if they don't want to do that axe-api pass error to express's default error handler( that sends HTML file with the error message ).

Today, I will add a basic error handler to template and dev-kit
